### PR TITLE
[update] get_balance_of

### PR DESCRIPTION
**Pull request by kichinosukey**
- Previously get_balance_of function do not work well.
- In this commit, this func return list object about tickets which user has.

### CODE REVIEW

**Comment by ks91** [comment]
Thank you for your contribution!
get_balance_of is very incomplete at the moment, and I think it should return the accumulated value of tickets of (currently not present) a specified type.
But I agree that there needs to be a function with which all the tickets a user has can be obtained. Please let me think about it.

**Comment by kichinosukey** [comment]
I understood what you think about get_balance_of and I have reviewed the code.
Currently get_balance_of return the balance of tickets user have obtained.
Please check the file changed.

And I will do pull-request with another commit about the function with which all the tickets a user has be obtained.

**Comment by ks91** [comment]
Thank you again for your contribution!
I think that get_balance_of() needs to take the type of the tickets somehow, because a ticket service may deal with different types of tickets whose values should not be accumulated.
Please let me think about.

**Comment by kichinosukey** [comment]
Since I'm going to send new pull request to about this topic, close this item.

**Pull request closed without merging**
